Redirect ECR upload help instructions to Summary page from Onboarding.
awslabs/aws-saas-boost pull request #302
Opened 2022-09-21 21:06 UTC by PoeppingT

Since AppConfig now supports multiple services, we cannot provide a simple set of instructions for uploading images into ECR like we did previously. This change changes the help message to be clear that there are now multiple repositories you may need to upload to and redirects the user to the Summary page, where those instructions can be found.

Fixes #301 
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-09-22 23:06 UTC, brtrvn requested changes
I'd just change the end of the sentence to ...instructions for each service _here_. (remove the colon)

2022-09-23 15:35 UTC, cfregly commented
This `/summary` solution presented here doesn't intuitively connect the dots that I need to understand how to introduce my docker image into the system.

Maybe it's as simple as modifying the "View details" link text below to say "View details on how to upload your Docker image" or something.

<img width="517" alt="image" src="https://user-images.githubusercontent.com/1438064/191998368-eb6c7d60-a4d5-4ba9-bed7-89cb023289b9.png">

Does that make sense?

2022-09-23 16:47 UTC, PoeppingT commented
> Kind of long, but do you understand my concern?

How about `View docker image upload instructions`?

2022-09-25 23:05 UTC, cfregly commented
Sure, that sounds good.  Thx!

2022-09-26 21:58 UTC, brtrvn approved these changes

2022-09-26 21:58 UTC, merged